// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ievtqteyyprrakteoyaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldnRxdGV5eXBycmFrdGVveWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTA0MTQsImV4cCI6MjA2Nzk2NjQxNH0.jJcuCh7PfGJrdVQHxC4IvlPdHo1Nz5ZfEPh-CKGSY8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});